sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t okellym2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true okellym2/react-test npm test

after_success:
  - docker build -t okellym2/multi-client ./client
  - docker build -t okellym2/multi-nginx ./nginx
  - docker build -t okellym2/multi-server ./server
  - docker build -t okellym2/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push okellym2/multi-client
  - docker push okellym2/multi-nginx
  - docker push okellym2/multi-server
  - docker push okellym2/multi-worker

deploy:
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: elasticbeanstalk-eu-west-1-382079606667Info
  bucket_path: docker-multi
  on:
    branch: master

  access:key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
